### PR TITLE
[develop] Feature/cicd scripts

### LINKED ISSUE #44: Posting Jenkin pipeline test result and log to PR
- Land DA Jenkin pipeline has been established successfully to build PRs and run Ctests at https://jenkins.epic.oarcloud.noaa.gov/job/land-da/job/Land%20DA%20Jenkinsfile/
- Need to add options to automatically posting test logs to PR
- Test artifacts can be posted in EPIC dashboard as well: https://noaa-epic-dashboard.s3.amazonaws.com/index.html 
- An example Jenkins test log is attached below for PR #23

### PR DESCRIPTION
**Pull request by BruceKropp-Raytheon**
## Description
Add initial CICD scripts and Jenkinsfile to support future PR validation stages.

### Anticipated changes to regression tests:
- [ ] Is baseline change expected ? None

## Subcomponents involved:
- [ ] apply_incr.fd (NOAA-PSL/land-apply_jedi_incr)
- [ ] ufs_model.fd (ufs-community/ufs-weather-model)
- [x] none

## Linked PR's and Issues:
None.

### Testing (for CM's):
- RDHPCS
    - [x] Hera
    - [x] Orion
    - [x] Hercules
- CI
  - [x] Completed. (draft builds and tests in Jenkins)
- ctests
  - [x] Completed
- PW-Clouds
  - [ ] AWS
  - [ ] AZURE
  - [ ] GCP

### CODE REVIEW

**Comment by BruceKropp-Raytheon** [comment]
Hera passed!
Orion and Hercules compute nodes are offline due to power failure. We will need to retry this PR build later.

**Comment by BruceKropp-Raytheon** [comment]
Passed on Hera, Hercules, and Orion.
Please Review.

**Comment by zach1221** [comment]
@chan-hoo I think these new cicd scripts and new jenkinsfile should be located in sorc/test/ci . What do you think? It would mean changing the name of one of the jenkinsfiles obviously.

**Review by zach1221 — APPROVED** [review]

**Comment by chan-hoo** [comment]
@zach1221, thanks for your review! merging.

**Pull request merged**
