### PR TITLE
Update to use the JEDI Skylab v4

### PR DESCRIPTION
**Pull request by rhaesung**
## Description
- JEDI analysis code bases have been updated to use the JEDI Skylab v4.0 release- this version can be built with all libraries on spack-stack version 1.3.0.

- 'srun' is replaced with 'mpiexec'.

- ctest is updated using a new s3 bucket.

- docutils version (docutils>=0.18.1) is updated for git action feature.

### Anticipated changes to regression tests:
- [ ] Is baseline change expected ? 

## Subcomponents involved:
- [X] DA_update
- [ ] vector2tile
- [ ] ufs-land-driver
- [ ] none

## Linked PR's and Issues:
https://github.com/ufs-community/land-DA_workflow/issues/24
https://github.com/ufs-community/land-DA/pull/3

### Testing (for CM's):
- RDHPCS
    - [X] Hera
    - [ ] Orion
    - [ ] Jet
    - [ ] Gaea
    - [ ] Cheyenne
- CI
  - [ ] Completed
- PW-Clouds
  - [ ] AWS
  - [ ] AZURE
  - [ ] GCP

### CODE REVIEW

**Comment by rhaesung** [comment]
@jkbk2004 'srun' is replaced with 'mpiexec'.

**Comment by zach1221** [comment]
@rhaesung ctests pass against your changes.
[Jenkins ctest PR-28.pdf](https://github.com/ufs-community/land-DA_workflow/files/12467299/Jenkins.ctest.PR-28.pdf)

**Comment by jkbk2004** [comment]
https://github.com/ufs-community/land-DA/pull/3 was merged. @rhaesung update hash and revert change in gitmodules.

**Comment by jkbk2004** [comment]
correct hash is https://github.com/ufs-community/land-DA/commit/e4171946e2dd6bb1829a8bba9198486df02815bb

**Review by jkbk2004 — APPROVED** [review]

**Comment by rhaesung** [comment]
> correct hash is [ufs-community/land-DA@e417194](https://github.com/ufs-community/land-DA/commit/e4171946e2dd6bb1829a8bba9198486df02815bb)

@jkbk2004 Thanks, done!

**Pull request merged**
