### PR TITLE
Feature/ctest update

### PR DESCRIPTION
**Pull request by clouden90**
## Description
Update  Orion modulefiles as well as the test_ufs_datm_land scripts to reflect recent changes of Orion role account and ufs_datm_land model updates.

How to test:
In your build folder:
../test/retrieve_data.sh/work2/noaa/epic-ps/ycteng/case/20230808/land-DA_workflow
salloc --ntasks 8 --exclusive --qos=debug --partition=debug --time=00:30:00 --account=epic
module use ../modulefiles && module load landda_orion.intel
export JEDI_EXECDIR=${JEDI_INSTALL}/fv3-bundle/build/bin
export RTPWD=/work2/noaa/epic-ps/ycteng/case/20230808/inputs/NEMSfv3gfs/develop-20230804/INTEL
export INPUTDATA_ROOT=/work2/noaa/epic-ps/ycteng/case/20230808/inputs/NEMSfv3gfs/input-data-20221101
ctest

Tests have been done on both Hera and Orion. Just be aware that the retrieve_data.sh step will take a while on Hera due to its extremely slow external internet connection.

### Anticipated changes to regression tests:
- [x] Is baseline change expected ? 

## Subcomponents involved:
- [ ] DA_update
- [ ] vector2tile
- [ ] ufs-land-driver
- [x] none

### Testing (for CM's):
- RDHPCS
    - [x] Hera
    - [x] Orion
    - [ ] Jet
    - [ ] Gaea
    - [ ] Cheyenne
- CI
  - [ ] Completed
- PW-Clouds
  - [ ] AWS
  - [ ] AZURE
  - [ ] GCP

### CODE REVIEW

**Comment by zach1221** [comment]
I tested this on Orion and it is successful. @clouden90 @rhaesung

**Comment by zach1221** [comment]
> I tested this on Orion and it is successful. @clouden90 @rhaesung

I can confirm hera is successful as well. @rhaesung let me know if you want the steps I used to run the tests.

**Comment by rhaesung** [comment]
> > I tested this on Orion and it is successful. @clouden90 @rhaesung
> 
> I can confirm hera is successful as well. @rhaesung let me know if you want the steps I used to run the tests.

Thanks, @zach1221! Yes, please share the steps on Hera.

**Comment by zach1221** [comment]
@rhaesung see below. Just replace the directories with your own.

git clone -b feature/ctest_update --recursive https://github.com/ufs-community/land-DA_workflow.git
cd land-DA_workflow
module load intel/2022.1.2 impi/2022.1.2
module use modulefiles
 module load landda_hera.intel 
mkdir build && cd build
 ecbuild ../ && make -j4
cd ..
 ./test/retrieve_data.sh $PWD
cd build
export JEDI_EXECDIR=${JEDI_INSTALL}/fv3-bundle/build/bin
export RTPWD=/scratch1/NCEPDEV/stmp2/role.epic/jenkins/workspace/inputs/NEMSfv3gfs/develop-20230804/INTEL
export INPUTDATA_ROOT=/scratch1/NCEPDEV/stmp2/role.epic/jenkins/workspace/inputs/NEMSfv3gfs/input-data-20221101
ctest

**Comment by rhaesung** [comment]
@clouden90 This pr was combined with pr23 (https://github.com/ufs-community/land-DA_workflow/pull/23) and merged. Can we close this one?

**Comment by clouden90** [comment]
Close now

**Pull request closed without merging**
