### PR TITLE
Update scripts to use JEDI skylab v7

### LINKED ISSUE #89: Analysis task fails with JEDI bundle skylab-v7
- The analysis task using JEDI fails with JEDI bundle skylab-v7.
- The current version of JEDI bundle in the land-DA_workflow is `skylab-v4`.
- The configuration yaml file should be updated.

### LINKED ISSUE #90: ex-scripts do not meet NCO implementation standards
The ex-scripts in the `scripts` directory need to be updated to meet the NCO implementation standards.

### LINKED ISSUE #91: Submodule `add_jedi_incr` needs to be added to sorc directly
- According to the NCO implementation standards, the source code of each executable should be located in the `sorc` directory.
- Currently, `add_jedi_incr` is a component of the submodule `DA_update`.
- The parameter files in `DA_update` can be moved to `parm` directly, and the submodule `DA_update` can be removed. This approach can reduce unnecessary dependencies.

### PR DESCRIPTION
**Pull request by chan-hoo**
## Description

- Update the version of JEDI skylab from v4 to v7.
- Update ex-scripts to use skylab v7 and to meet the NCO implementation standards.
- Replace the submodule `DA_update` with `apply_incr` directly.
- Add the templates and configuration files in `DA_update` to `parm`.
- Create the `ush` directory.

### Anticipated changes to regression tests:
- [ ] Is baseline change expected ? 

## Subcomponents involved:
- [ ] DA_update (ufs-community/land-DA)
- [ ] ufsLand.fd (NOAA-EPIC/ufs-land-driver-emc-dev)
- [ ] ufs_model.fd (ufs-community/ufs-weather-model)
- [ ] vector2tile_converter.fd (NOAA-PSL/land-vector2tile)
- [ ] none

## Linked PR's and Issues:

Fixes Issues #46, #89, #90, and #91

### Testing (for CM's):
- RDHPCS
    - [ ] Hera
    - [x] Orion
    - [ ] Jet
    - [ ] Gaea
    - [ ] Cheyenne
- CI
  - [ ] Completed
- PW-Clouds
  - [ ] AWS
  - [ ] AZURE
  - [ ] GCP

### CODE REVIEW

**Comment by chan-hoo** [comment]
In Ctest, tests 5 and 6 failed when the result files were compared to the test_base files:
- test 5 (tile2vector)
```
Not equal to tolerance rtol=1e-08, atol=1e-06

Mismatched elements: 471 / 128254 (0.367%)
Max absolute difference: 0.00412437
Max relative difference: 0.04656209
```
- test 6 (land driver)
```
AssertionError:
Not equal to tolerance rtol=1e-08, atol=1e-06

Mismatched elements: 443 / 128254 (0.345%)
Max absolute difference: 0.0111796
Max relative difference: 0.09948057
```
This might be caused by the new version of JEDI (skylab v.7), but I am not sure.

**Comment by jkbk2004** [comment]
> In Ctest, tests 5 and 6 failed when the result files were compared to the test_base files:
> 
> * test 5 (tile2vector)
> 
> ```
> Not equal to tolerance rtol=1e-08, atol=1e-06
> 
> Mismatched elements: 471 / 128254 (0.367%)
> Max absolute difference: 0.00412437
> Max relative difference: 0.04656209
> ```
> 
> * test 6 (land driver)
> 
> ```
> AssertionError:
> Not equal to tolerance rtol=1e-08, atol=1e-06
> 
> Mismatched elements: 443 / 128254 (0.345%)
> Max absolute difference: 0.0111796
> Max relative difference: 0.09948057
> ```
> 
> This might be caused by the new version of JEDI (skylab v.7), but I am not sure.

No surprise to see impact on the computed result with jedi bundle update even along with stack update (previously installed before this pr). It will be good to check unit of mean/max diff values. Scatter plots for sanity check.

**Comment by chan-hoo** [comment]
@jkbk2004, with the new base files:
```
Orion-login-1[41] chjeon$ ctest --rerun-failed
Test project /work/noaa/epic/chjeon/landda_sub/land-DA_workflow/sorc/build
    Start 5: test_tile2vector
1/2 Test #5: test_tile2vector .................   Passed    2.37 sec
    Start 6: test_land_driver
2/2 Test #6: test_land_driver .................   Passed    7.82 sec

100% tests passed, 0 tests failed out of 2
```

**Comment by chan-hoo** [comment]
```
Orion-login-1[7] chjeon$ ctest
Test project /work/noaa/epic/chjeon/landda_sub/land-DA_workflow/sorc/build
    Start 1: test_vector2tile
1/7 Test #1: test_vector2tile .................   Passed   12.56 sec
    Start 2: test_create_ens
2/7 Test #2: test_create_ens ..................   Passed   19.52 sec
    Start 3: test_letkfoi_snowda
3/7 Test #3: test_letkfoi_snowda ..............   Passed   71.65 sec
    Start 4: test_apply_jediincr
4/7 Test #4: test_apply_jediincr ..............   Passed    4.44 sec
    Start 5: test_tile2vector
5/7 Test #5: test_tile2vector .................   Passed   13.50 sec
    Start 6: test_land_driver
6/7 Test #6: test_land_driver .................   Passed    9.43 sec
    Start 7: test_ufs_datm_land
7/7 Test #7: test_ufs_datm_land ...............   Passed  513.33 sec

100% tests passed, 0 tests failed out of 7

Total Test time (real) = 644.70 sec
```

**Review by jkbk2004 — APPROVED** [review]

**Pull request merged**
