### PR TITLE
Change structure of output and log directories

### LINKED ISSUE #74: Need to make structure of output directory clear
- The directory structure of the output files, defined in the land_analysis.yaml file is not clear.
- The log file `slurm_` needs to be moved to the log directory.
- The current directory structure does not meet the NCO implementation standards.

### PR DESCRIPTION
**Pull request by chan-hoo**
## Description

- To make the path of the output files clear, its structure is modified.
- Log files are moved into the COM directory.
- This change partially follows the NCO implementation standards (path under COMROOT).

### Anticipated changes to regression tests:
- [ ] Is baseline change expected ? 

## Subcomponents involved:
- [ ] DA_update (ufs-community/land-DA)
- [ ] ufsLand.fd (NOAA-EPIC/ufs-land-driver-emc-dev)
- [ ] ufs_model.fd (ufs-community/ufs-weather-model)
- [ ] vector2tile_converter.fd (NOAA-PSL/land-vector2tile)
- [x] none

## Linked PR's and Issues:

- Resolves Issues #71 , #74 

### Testing (for CM's):
- RDHPCS
    - [x] Hera
    - [x] Orion
    - [ ] Jet
    - [ ] Gaea
    - [ ] Cheyenne
- CI
  - [ ] Completed
- PW-Clouds
  - [ ] AWS
  - [ ] AZURE
  - [ ] GCP

### CODE REVIEW

**Comment by chan-hoo** [comment]
```
Orion-login-4[11] chjeon$ ctest
Test project /work/noaa/epic/chjeon/landda_test/land-DA_workflow/sorc/build
    Start 1: test_vector2tile
1/7 Test #1: test_vector2tile .................   Passed    7.99 sec
    Start 2: test_create_ens
2/7 Test #2: test_create_ens ..................   Passed    8.77 sec
    Start 3: test_letkfoi_snowda
3/7 Test #3: test_letkfoi_snowda ..............   Passed   61.51 sec
    Start 4: test_apply_jediincr
4/7 Test #4: test_apply_jediincr ..............   Passed    4.86 sec
    Start 5: test_tile2vector
5/7 Test #5: test_tile2vector .................   Passed   14.08 sec
    Start 6: test_land_driver
6/7 Test #6: test_land_driver .................   Passed   10.95 sec
    Start 7: test_ufs_datm_land
7/7 Test #7: test_ufs_datm_land ...............   Passed  586.78 sec

100% tests passed, 0 tests failed out of 7

Total Test time (real) = 695.06 sec

```

**Comment by zach1221** [comment]
@chan-hoo don't we need to remove line 347 of app_build.sh or replace with "module purge'? I thought this was necessary to build successfully?

**Comment by chan-hoo** [comment]
@zach1221, removed.
```
Orion-login-4[4] chjeon$ ctest
Test project /work/noaa/epic/chjeon/landda_test/land-DA_workflow/sorc/build
    Start 1: test_vector2tile
1/7 Test #1: test_vector2tile .................   Passed    8.55 sec
    Start 2: test_create_ens
2/7 Test #2: test_create_ens ..................   Passed   13.62 sec
    Start 3: test_letkfoi_snowda
3/7 Test #3: test_letkfoi_snowda ..............   Passed   73.37 sec
    Start 4: test_apply_jediincr
4/7 Test #4: test_apply_jediincr ..............   Passed    5.00 sec
    Start 5: test_tile2vector
5/7 Test #5: test_tile2vector .................   Passed   12.93 sec
    Start 6: test_land_driver
6/7 Test #6: test_land_driver .................   Passed    8.49 sec
    Start 7: test_ufs_datm_land
7/7 Test #7: test_ufs_datm_land ...............   Passed  590.54 sec

100% tests passed, 0 tests failed out of 7
```

**Comment by jkbk2004** [comment]
@chan-hoo I can approve if you are ok with my last two commits. There is jenkins pipeline ctest failure (test 6), which is nothing to do with this pr. we can capture after merging this pr. let me know.

**Comment by chan-hoo** [comment]
@jkbk2004, they look good. please approve this pr.

**Review by jkbk2004 — APPROVED** [review]

**Pull request merged**
