### PR TITLE
Module versions are controlled in versions to meet NCO standards

### LINKED ISSUE #52: Versions of modules should be controlled in centralized location
To meet the NCO standards, the versions of the modules used in the tasks should be controlled in the `versions` directory (NCO standards, pp 19, Table 3). It should contain `build.ver` and `run.ver` to compile and run, respectively.

### LINKED ISSUE #55: Unused files need to be removed
Some files that are not used by the app should be removed:
- configures (dir)
- aladates.sh
- README_git
- release.environment
- settings_DA_cycle_era5
- settings_DA_cycle_gswp3
- settings_DA_test
- do_submit_cycle.sh
- do_submit_test.sh
- incdate.sh
- module_check.sh
- submit_cycle.sh
- check_test.sh
- check_release_outputs.sh

### PR DESCRIPTION
**Pull request by chan-hoo**
## Description

- To meet the NCO implementation standards, the versions of modules are controlled by the files `build_ver` and `run_ver` in the `versions` directory.
- Remove unnecessary files.

### Anticipated changes to regression tests:
- [ ] Is baseline change expected ? 

## Subcomponents involved:
- [ ] DA_update (ufs-community/land-DA)
- [ ] ufsLand.fd (NOAA-EPIC/ufs-land-driver-emc-dev)
- [ ] ufs_model.fd (ufs-community/ufs-weather-model)
- [ ] vector2tile_converter.fd (NOAA-PSL/land-vector2tile)
- [x] none

## Linked PR's and Issues:

Closes the issues: ufs-community/land-DA_workflow/issues/52 and ufs-community/land-DA_workflow/issues/55

### Testing (for CM's):
- RDHPCS
    - [x] Hera
    - [x] Orion
    - [ ] Jet
    - [ ] Gaea
    - [ ] Cheyenne
- CI
  - [ ] Completed
- PW-Clouds
  - [ ] AWS
  - [ ] AZURE
  - [ ] GCP

### CODE REVIEW

**Comment by jkbk2004** [comment]
@chan-hoo any comment?
```
(base) jongkim@Orion-login-3:/work/noaa/epic/jongkim/land-DA/pr-63$ module use modulefiles/
Lmod has detected the following error:  The following module(s) are unknown: "zstd/1.5.2" "pkg-config/0.27.1"
"py-python-dateutil/2.8.2" "g2tmpl/1.10.2" "parallelio/2.5.9" "curl/7.85.0" "miniconda/3.9.7" "gftl-shared/1.5.0"
"netcdf-c/4.9.2" "netcdf-fortran/4.6.0" "git-lfs/2.12.0" "ip/3.3.3" "py-numexpr/2.8.3" "crtm-fix/2.4.0_emc" "zlib/1.2.13"
"esmf/8.3.0b09" "stack-intel-oneapi-mpi/2021.5.1" "ufs-pyenv" "py-pyyaml/6.0" "hdf5/1.14.0" "jasper/2.0.32" "py-cython/0.29.32"
"py-pytz/2022.2.1" "ecbuild/3.6.5" "libjpeg/2.1.0" "crtm/2.4.0" "py-packaging/21.3" "w3emc/2.9.2" "parallel-netcdf/1.12.2"
"py-jinja2/3.1.2" "bacio/2.4.1" "py-netcdf4/1.5.3" "stack-intel/2022.0.2" "py-markupsafe/2.1.1" "py-f90nml/1.4.3"
"py-pandas/1.4.0" "py-cftime/1.0.3.4" "mapl/2.22.0-esmf-8.3.0b09" "g2/3.4.5" "openblas/0.3.19" "py-setuptools/59.4.0"
"py-numpy/1.22.3" "fms/2022.04" "py-pyparsing/3.0.9" "py-six/1.16.0" "gftl/1.8.1" "py-bottleneck/1.3.5" "stack-python/3.9.7"
"yafyaml/0.5.1" "libpng/1.6.37"
```

**Comment by jkbk2004** [comment]
@chan-hoo maybe need to double check version numbers of packges

**Comment by chan-hoo** [comment]
@jkbk2004, before running `module use modulefiles`, did you source the version file like `source versions/build.ver_orion`?

**Comment by jkbk2004** [comment]
```
(base) jongkim@Orion-login-3:/work/noaa/epic/jongkim/land-DA/pr-63/build$ ctest
Test project /work/noaa/epic/jongkim/land-DA/pr-63/build
    Start 1: test_vector2tile
1/7 Test #1: test_vector2tile .................   Passed    6.50 sec
    Start 2: test_create_ens
2/7 Test #2: test_create_ens ..................   Passed   10.82 sec
    Start 3: test_letkfoi_snowda
3/7 Test #3: test_letkfoi_snowda ..............   Passed   54.98 sec
    Start 4: test_apply_jediincr
4/7 Test #4: test_apply_jediincr ..............   Passed    4.19 sec
    Start 5: test_tile2vector
5/7 Test #5: test_tile2vector .................   Passed    8.55 sec
    Start 6: test_land_driver
6/7 Test #6: test_land_driver .................   Passed    8.22 sec
    Start 7: test_ufs_datm_land
7/7 Test #7: test_ufs_datm_land ...............   Passed  278.73 sec

100% tests passed, 0 tests failed out of 7

Total Test time (real) = 372.02 sec
```

**Review by jkbk2004 — APPROVED** [review]

**Pull request merged**
