### PR TITLE
Update hash of ufs weather model

### LINKED ISSUE #145: Need to update hash of ufs weather model
- The current hash of the ufs weather model is out-of-date.
- Its hash needs to be updated.
- The regression tests related to land-DA in the ufs weather model:
```
### CDEPS Data Atmosphere tests with LND ###
COMPILE | datm_cdeps_land | intel | -DAPP=LND | - wcoss2 | fv3 |
RUN | datm_cdeps_lnd_gswp3                              | - wcoss2                             | baseline |
RUN | datm_cdeps_lnd_era5                               | - wcoss2                             | baseline |
RUN | datm_cdeps_lnd_era5_rst                           | - wcoss2 noaacloud                   |          | datm_cdeps_lnd_era5
```

### PR DESCRIPTION
**Pull request by chan-hoo**
## Description

- Update the hash of the ufs weather model.
- Update module files.
- Update the ctest scripts

To run a new ctest script:
```
cd sorc/test
./run_ctest_platform.sh
```

### Anticipated changes to regression tests:
- [x] Is baseline change expected ? 

## Subcomponents involved:
- [ ] apply_incr.fd (NOAA-PSL/land-apply_jedi_incr)
- [x] ufs_model.fd (ufs-community/ufs-weather-model)
- [ ] none

## Linked PR's and Issues:

Resolves Issue #145 

### Testing (for CM's):
- RDHPCS
    - [x] Hera
    - [x] Orion
    - [x] Hercules
- CI
  - [ ] Completed
- WE2E
  - [ ] Completed
- PW-Clouds
  - [ ] AWS
  - [ ] AZURE
  - [ ] GCP

### CODE REVIEW

**Comment by chan-hoo** [comment]
```
+ ctest
Test project /work/noaa/epic/chjeon/landda_test/land-DA_workflow/sorc/build
    Start 1: test_create_ens
1/4 Test #1: test_create_ens ..................   Passed    2.47 sec
    Start 2: test_letkfoi_snowda
2/4 Test #2: test_letkfoi_snowda ..............   Passed    4.80 sec
    Start 3: test_apply_jediincr
3/4 Test #3: test_apply_jediincr ..............   Passed    2.43 sec
    Start 4: test_ufs_datm_land
4/4 Test #4: test_ufs_datm_land ...............   Passed   59.31 sec

100% tests passed, 0 tests failed out of 4

Total Test time (real) =  69.02 sec
```

**Comment by jkbk2004** [comment]
@chan-hoo can you test with limited resource in ufs.configure as we have develop? It's good to see fast run with more PEs. But I think limited resource option is still good to maintain others: container, run on clouds, etc.

**Comment by chan-hoo** [comment]
On Hera:
```
Test project /scratch2/NAGAPE/epic/Chan-hoo.Jeon/landda_test/land-DA_workflow/sorc/build
    Start 1: test_create_ens
1/4 Test #1: test_create_ens ..................   Passed    4.61 sec
    Start 2: test_letkfoi_snowda
2/4 Test #2: test_letkfoi_snowda ..............   Passed   16.43 sec
    Start 3: test_apply_jediincr
3/4 Test #3: test_apply_jediincr ..............   Passed    1.70 sec
    Start 4: test_ufs_datm_land
4/4 Test #4: test_ufs_datm_land ...............   Passed   42.74 sec

100% tests passed, 0 tests failed out of 4

Total Test time (real) =  65.49 sec
```

**Comment by chan-hoo** [comment]
On Orion:
```
Test project /work/noaa/epic/chjeon/landda_test/land-DA_workflow/sorc/build
    Start 1: test_create_ens
1/4 Test #1: test_create_ens ..................   Passed   10.80 sec
    Start 2: test_letkfoi_snowda
2/4 Test #2: test_letkfoi_snowda ..............   Passed   31.44 sec
    Start 3: test_apply_jediincr
3/4 Test #3: test_apply_jediincr ..............   Passed    2.49 sec
    Start 4: test_ufs_datm_land
4/4 Test #4: test_ufs_datm_land ...............   Passed   70.28 sec

100% tests passed, 0 tests failed out of 4

Total Test time (real) = 115.11 sec
```

**Comment by chan-hoo** [comment]
On Hercules:
```
Test project /work/noaa/epic/chjeon/landda_test_hercules/land-DA_workflow/sorc/build
    Start 1: test_create_ens
1/4 Test #1: test_create_ens ..................   Passed   55.87 sec
    Start 2: test_letkfoi_snowda
2/4 Test #2: test_letkfoi_snowda ..............   Passed  280.26 sec
    Start 3: test_apply_jediincr
3/4 Test #3: test_apply_jediincr ..............   Passed    2.50 sec
    Start 4: test_ufs_datm_land
4/4 Test #4: test_ufs_datm_land ...............   Passed   69.36 sec
```

**Comment by chan-hoo** [comment]
@jkbk2004, plz review this PR again.

**Review by jkbk2004 — APPROVED** [review]

**Pull request merged**
