### PR TITLE
Updates for v1.1.0 release

### PR DESCRIPTION
**Pull request by gspetro-NOAA**
## Description
Minor update(s) for release: 
- Update clone command for v1.1.0 release. 
- Update container names & some container-related instructions.

Can view docs on my fork: https://gsp-land-da-wf.readthedocs.io/en/release-public-v1.1.0/Container.html

### Anticipated changes to regression tests:
- [ ] Is baseline change expected ? NO.

## Subcomponents involved:
- [ ] DA_update
- [ ] vector2tile
- [ ] ufs-land-driver
- [X] none

## Linked PR's and Issues:
N/A.

### Testing (for CM's):
- RDHPCS
    - [ ] Hera
    - [ ] Orion
    - [ ] Jet
    - [ ] Gaea
    - [ ] Cheyenne
- CI
  - [ ] Completed
- PW-Clouds
  - [ ] AWS
  - [ ] AZURE
  - [ ] GCP

### CODE REVIEW

**Review by rhaesung — APPROVED** [review]

**Comment by jkbk2004** [comment]
@gspetro-NOAA do you still need to work on ?

**Comment by gspetro-NOAA** [comment]
@jkbk2004 I was waiting till Mark and Eddie staged the release containers so that I could update the info all in one PR. If you'd rather do it in 2 PRs tho, that's fine. Just let me know.

**Comment by jkbk2004** [comment]
I think it makes a sense to update run container executable script with ubuntu20.04-intel-ue-landda-v1.1.0.img. @gspetro-NOAA do you want me to update to your branch?

**Comment by gspetro-NOAA** [comment]
@jkbk2004 No need--I'm working on that now!

**Comment by jkbk2004** [comment]
can we update https://github.com/gspetro-NOAA/land-DA_workflow/blob/a7799aea5195c6810c167a682d3c6416caf902c0/run_container_executable.sh#L7 ?

**Pull request merged**
