### PR TITLE
Add new task to plot analysis

### LINKED ISSUE #106: Need a task to plot result of analysis
- Need to add a new task to plot the results of the analysis task.

### PR DESCRIPTION
**Pull request by chan-hoo**
## Description

- Adds a new task `plot_stats` to plot the result of the `analysis` task.
- Sample figures: 
hofx_oma_20000104_scatter
hofx_oma_20000104_histogram

### Anticipated changes to regression tests:
- [ ] Is baseline change expected ? 

## Subcomponents involved:
- [ ] apply_incr.fd (NOAA-PSL/land-apply_jedi_incr)
- [ ] ufsLand.fd (NOAA-EPIC/ufs-land-driver-emc-dev)
- [ ] ufs_model.fd (ufs-community/ufs-weather-model)
- [ ] vector2tile_converter.fd (NOAA-PSL/land-vector2tile)
- [x] none

## Linked PR's and Issues:

Resolves Issue #106 

### Testing (for CM's):
- RDHPCS
    - [ ] Hera
    - [x] Orion
    - [ ] Jet
    - [ ] Gaea
    - [ ] Cheyenne
- CI
  - [x] Completed
- PW-Clouds
  - [ ] AWS
  - [ ] AZURE
  - [ ] GCP

### CODE REVIEW

**Comment by chan-hoo** [comment]
```
    Start 1: test_vector2tile
1/7 Test #1: test_vector2tile .................   Passed   38.48 sec
    Start 2: test_create_ens
2/7 Test #2: test_create_ens ..................   Passed   18.53 sec
    Start 3: test_letkfoi_snowda
3/7 Test #3: test_letkfoi_snowda ..............   Passed   62.33 sec
    Start 4: test_apply_jediincr
4/7 Test #4: test_apply_jediincr ..............   Passed    5.66 sec
    Start 5: test_tile2vector
5/7 Test #5: test_tile2vector .................   Passed   10.54 sec
    Start 6: test_land_driver
6/7 Test #6: test_land_driver .................   Passed   12.95 sec
    Start 7: test_ufs_datm_land
7/7 Test #7: test_ufs_datm_land ...............   Passed  567.80 sec

100% tests passed, 0 tests failed out of 7

Total Test time (real) = 716.66 sec
```

**Comment by chan-hoo** [comment]
scatter
with new colormap

**Comment by chan-hoo** [comment]
scatter2

**Comment by chan-hoo** [comment]
scatter3

**Comment by chan-hoo** [comment]
scatter4

**Comment by chan-hoo** [comment]
histgram

**Comment by chan-hoo** [comment]
scatter5

**Review by jkbk2004 — APPROVED** [review]

**Pull request merged**
